dataset:
  path_to_data: "generated_data"
  fraction_of_data: 1.0         # 1.0 means use the full dataset

  inputs:
    time_days: "MinMax"
    power_W_g: "MinMax"
    int_p_W: "MinMax"
    fuel_temp_K: "MinMax"
    mod_temp_K: "MinMax"
    clad_temp_K: "MinMax"
    mod_density_g_cm3: "MinMax"
    boron_ppm: "MinMax"
    burnup_MWd_per_kg: "MinMax"
    U238: "Standard"
  
  # Target features with scaling
  targets:
    U238: "Standard"

  # Data loader configuration
  train:
    batch_size: 2048
  val:
    batch_size: 8192

model:
  name: "SimpleDNN"
  layers: [64,64]         
  dropout_probability: 0.1
  activation: "relu"  # Options: relu, tanh, sigmoid, leaky_relu, elu, gelu
  output_activation: "none"  # Options: none, sigmoid, tanh, softplus

train:
  loss: "mse"
  learning_rate: 1.0e-5
  weight_decay: 5.0e-4
  lr_scheduler_patience: 10
  num_epochs: 1000
  early_stopping_patience: 20

  dropout_probability: 0.1   

output:
  result_dir: "results/${model.name}/"

runtime:
  mode: "train"    # Options: train, train_from_ckp
  ckp_path: 'results/SimpleDNN/best-SimpleDNN-epoch=397.ckpt'

  device: "cude"
  seed: 42
  drop_last: false
  num_workers: 10
