name: nuclear-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openmc
  - pytorch
  - pytorch-lightning
  - numpy
  - pandas
  - matplotlib
  - h5py
  - optuna
  - pytest         
  - pip
  - pip:
    - -e .